# Generated by Django 5.1.4 on 2024-12-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('popular_season', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='TravelDestination',
        ),
    ]
