# Generated by Django 5.1.4 on 2024-12-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_director_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='release_year',
            new_name='realizer_year',
        ),
    ]
